### ISSUE TITLE
Confirm what salt value to use when creating a token

### ISSUE THREAD

**Issue by plafer** [informalsystems/sovereign-sdk#10]
When creating a token, we [currently set the salt](https://github.com/informalsystems/sovereign-sdk/blob/54db60b0f4d03ca4029e0679a888dc37187db34c/module-system/module-implementations/sov-ibc-transfer/src/context.rs#L304) to `0`.

Perhaps @preston-evans98 can provide insight into how to properly set that value?

**Comment by preston-evans98** [comment]
Hey @plafer! You can use any salt value you want. The salt is used to calculate the token's address, so you only need to change the salt if you want to deploy multiple tokens with the same name from the same address (which I suppose might be the case in IBC?)

**Comment by plafer** [comment]
Oh I see. Then in that case we can always just use `0`, since ICS-20 tokens coming from other chains are guaranteed to have a unique name.

Thanks for the clarification!
